# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d028272745517fab45e458acf2b44cf6c8b6333bf765735a303ffaca211729aa6062bf15d351533091e488aee66b2674b54a1c697cb7dace53245d6ef3f35c5c

test:
  secret_key_base: 0645abda07c188889cceb7889cb2c7dc7a797b7bca180a480f9886dff847cb80f0ccd50983d11c6698a5c79eb9a1015e6930c8a3a8fb2abcc7a3b1f6b515efa2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
